### ISSUE TITLE
Making Kraken assembly directory:     0 / 0 assemblies

### ISSUE THREAD

**Issue by nashanghenzan** [rrwick/Metagenomics-Index-Correction#13]
it found assamblys, but can't convert to format for kraken2
here is my code `python tax_from_gtdb.py --gtdb taxID_info.tsv --assemblies /mnt/shujuku/gtdb/release207_v2/fastani/database/GCF --nodes nodes.dmp --names names.dmp --kraken_dir gtdb_genomes`

**Comment by davidbio** [comment]
Hi @nashanghenzan,
Any luck in getting this solved?
Where did you find the link to the assemblies?
I don't understand where they come from.

EDIT:
You have to download the assemblies from NCBI RefSeq, it works.
I tried with Archaea first, this is a valid URL for one of the necessary assemblies:
[https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/900/103/415/GCF_900103415.1_IMG-taxon_2593339167_annotated_assembly/GCF_900103415.1_IMG-taxon_2593339167_annotated_assembly_genomic.fna.gz](https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/900/103/415/GCF_900103415.1_IMG-taxon_2593339167_annotated_assembly/GCF_900103415.1_IMG-taxon_2593339167_annotated_assembly_genomic.fna.gz)

I will make a script to download them automatically and put them in a folder and share the script if successful.

EDIT2:
So I believe that the assemblies should be downloaded with the Kraken2 download script and the resulting folder can then be provided to this script.
